version: "3.4"
services:
    frontend:
        build: 
            context: ./frontend
        #image: frontend:latest
        container_name: frontend
        hostname: frontend
        ports:
            - "80:8080"
        depends_on:
            - backend
    backend:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        build: ./backend
        #image: backend:latest
        container_name: backend
        hostname: backend
        ports:
            - "5000:80"
            - "44349:443"
        networks:
            - overlay
        extra_hosts:
            - "DEMOTEST:10.0.75.1"
        depends_on:
            - sql.data
    sql.data:
        image: crobles10/summit_dev:3.0
        container_name: sql.data
        hostname: sql.data
        ports:
            - "1433:1433"
        networks:
            - overlay

networks:
  overlay: